"""Add user_id to search_cache

Revision ID: 06df5c3d40ae
Revises: dd83c45cd8b2
Create Date: 2025-06-21 05:30:46.466202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06df5c3d40ae'
down_revision = 'dd83c45cd8b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=234),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=234),
               existing_nullable=False)
    # ### end Alembic commands ###
