"""Fix relationship casing

Revision ID: 20c379c9f23f
Revises: 767849fd6181
Create Date: 2025-06-17 14:03:46.579369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c379c9f23f'
down_revision = '767849fd6181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
