"""Add User and SearchCache tables

Revision ID: 5b8bddd26d98
Revises: 
Create Date: 2025-05-25 14:58:24.879187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b8bddd26d98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=234), nullable=False),
    sa.Column('password_has', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('search_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('search_term', sa.String(), nullable=False),
    sa.Column('results', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('use_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['use_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_cache')
    op.drop_table('users')
    # ### end Alembic commands ###
