"""Fix user relationship case

Revision ID: 767849fd6181
Revises: 5801e45ba3f7
Create Date: 2025-06-17 13:35:27.064232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767849fd6181'
down_revision = '5801e45ba3f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_cache', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('search_cache_use_id_fkey', 'search_cache', type_='foreignkey')
    op.create_foreign_key(None, 'search_cache', 'users', ['user_id'], ['id'])
    op.drop_column('search_cache', 'use_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_cache', sa.Column('use_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'search_cache', type_='foreignkey')
    op.create_foreign_key('search_cache_use_id_fkey', 'search_cache', 'users', ['use_id'], ['id'])
    op.drop_column('search_cache', 'user_id')
    # ### end Alembic commands ###
