"""initial migration

Revision ID: 91a5770eb837
Revises: 06df5c3d40ae
Create Date: 2025-06-23 04:04:17.369670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a5770eb837'
down_revision = '06df5c3d40ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_has')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_has', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
