"""Add password_hash column to users

Revision ID: 950edcad99f9
Revises: 5b8bddd26d98
Create Date: 2025-05-26 01:35:06.002371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950edcad99f9'
down_revision = '5b8bddd26d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
