"""Fix relationship casing

Revision ID: b3f001c247d4
Revises: 20c379c9f23f
Create Date: 2025-06-17 14:08:01.408244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f001c247d4'
down_revision = '20c379c9f23f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
